# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulate_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 250)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.rssi_picam1 = QtWidgets.QSpinBox(self.centralwidget)
        self.rssi_picam1.setEnabled(True)
        self.rssi_picam1.setMinimum(0)
        self.rssi_picam1.setMaximum(100)
        self.rssi_picam1.setProperty("value", 90)
        self.rssi_picam1.setObjectName("rssi_picam1")
        self.gridLayout.addWidget(self.rssi_picam1, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 15))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.btn_gpio_B = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gpio_B.setObjectName("btn_gpio_B")
        self.gridLayout.addWidget(self.btn_gpio_B, 9, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 3, 1, 1)
        self.rain = QtWidgets.QCheckBox(self.centralwidget)
        self.rain.setText("")
        self.rain.setObjectName("rain")
        self.gridLayout.addWidget(self.rain, 6, 3, 1, 1)
        self.btn_gpio_A = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gpio_A.setObjectName("btn_gpio_A")
        self.gridLayout.addWidget(self.btn_gpio_A, 9, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 0, 4, 1, 1)
        self.btn_send_Info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send_Info.setObjectName("btn_send_Info")
        self.gridLayout.addWidget(self.btn_send_Info, 9, 3, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 4, 1, 1)
        self.wind_dir = QtWidgets.QSpinBox(self.centralwidget)
        self.wind_dir.setEnabled(True)
        self.wind_dir.setMinimum(-90)
        self.wind_dir.setMaximum(90)
        self.wind_dir.setObjectName("wind_dir")
        self.gridLayout.addWidget(self.wind_dir, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 3, 1, 1)
        self.rssi_picam2 = QtWidgets.QSpinBox(self.centralwidget)
        self.rssi_picam2.setEnabled(True)
        self.rssi_picam2.setMinimum(0)
        self.rssi_picam2.setMaximum(100)
        self.rssi_picam2.setProperty("value", 95)
        self.rssi_picam2.setObjectName("rssi_picam2")
        self.gridLayout.addWidget(self.rssi_picam2, 4, 4, 1, 1)
        self.AccuVoltage = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.AccuVoltage.setDecimals(1)
        self.AccuVoltage.setMinimum(9.0)
        self.AccuVoltage.setMaximum(12.6)
        self.AccuVoltage.setSingleStep(0.1)
        self.AccuVoltage.setProperty("value", 11.8)
        self.AccuVoltage.setObjectName("AccuVoltage")
        self.gridLayout.addWidget(self.AccuVoltage, 8, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setMinimumSize(QtCore.QSize(0, 15))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 3, 1, 1)
        self.wind_speed = QtWidgets.QSpinBox(self.centralwidget)
        self.wind_speed.setMaximum(30)
        self.wind_speed.setProperty("value", 3)
        self.wind_speed.setObjectName("wind_speed")
        self.gridLayout.addWidget(self.wind_speed, 2, 3, 1, 1)
        self.listWBtn = QtWidgets.QListWidget(self.centralwidget)
        self.listWBtn.setObjectName("listWBtn")
        self.gridLayout.addWidget(self.listWBtn, 2, 2, 7, 1)
        self.listBaseB = QtWidgets.QListWidget(self.centralwidget)
        self.listBaseB.setObjectName("listBaseB")
        self.gridLayout.addWidget(self.listBaseB, 2, 1, 7, 1)
        self.listBaseA = QtWidgets.QListWidget(self.centralwidget)
        self.listBaseA.setObjectName("listBaseA")
        self.gridLayout.addWidget(self.listBaseA, 2, 0, 7, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chrono Simulate Bases"))
        self.label_4.setText(_translate("MainWindow", "Base B"))
        self.label_12.setText(_translate("MainWindow", "Speed\n"
"(m/s)"))
        self.label_3.setText(_translate("MainWindow", "Base A"))
        self.btn_gpio_B.setText(_translate("MainWindow", "GPIO Btn"))
        self.label_13.setText(_translate("MainWindow", "Dir (°)"))
        self.btn_gpio_A.setText(_translate("MainWindow", "GPIO Btn"))
        self.label_26.setText(_translate("MainWindow", "PiCAM1 RSSI"))
        self.btn_send_Info.setText(_translate("MainWindow", "Send info"))
        self.label_27.setText(_translate("MainWindow", "PICAM2 RSSI"))
        self.label_5.setText(_translate("MainWindow", "Wireless btn"))
        self.label_14.setText(_translate("MainWindow", "Rain"))
        self.label_25.setText(_translate("MainWindow", "Accu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
