# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulate_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 332)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.AccuPicam1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.AccuPicam1.setDecimals(1)
        self.AccuPicam1.setMinimum(9.0)
        self.AccuPicam1.setMaximum(12.6)
        self.AccuPicam1.setSingleStep(0.1)
        self.AccuPicam1.setProperty("value", 11.8)
        self.AccuPicam1.setObjectName("AccuPicam1")
        self.gridLayout.addWidget(self.AccuPicam1, 7, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setMinimumSize(QtCore.QSize(0, 15))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 10, 3, 1, 1)
        self.listBaseA = QtWidgets.QListWidget(self.centralwidget)
        self.listBaseA.setMinimumSize(QtCore.QSize(100, 0))
        self.listBaseA.setObjectName("listBaseA")
        self.gridLayout.addWidget(self.listBaseA, 2, 0, 11, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 3, 1, 3)
        self.wind_speed = QtWidgets.QSpinBox(self.centralwidget)
        self.wind_speed.setMaximum(30)
        self.wind_speed.setProperty("value", 3)
        self.wind_speed.setObjectName("wind_speed")
        self.gridLayout.addWidget(self.wind_speed, 0, 4, 1, 1)
        self.speedProcessing = QtWidgets.QCheckBox(self.centralwidget)
        self.speedProcessing.setObjectName("speedProcessing")
        self.gridLayout.addWidget(self.speedProcessing, 0, 5, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 9, 3, 1, 3)
        self.rain = QtWidgets.QCheckBox(self.centralwidget)
        self.rain.setObjectName("rain")
        self.gridLayout.addWidget(self.rain, 5, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 3, 1, 3)
        self.picam2Processing = QtWidgets.QCheckBox(self.centralwidget)
        self.picam2Processing.setObjectName("picam2Processing")
        self.gridLayout.addWidget(self.picam2Processing, 10, 5, 2, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 8, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setMinimumSize(QtCore.QSize(0, 15))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 3, 1, 1)
        self.AccuPicam2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.AccuPicam2.setDecimals(1)
        self.AccuPicam2.setMinimum(9.0)
        self.AccuPicam2.setMaximum(12.6)
        self.AccuPicam2.setSingleStep(0.1)
        self.AccuPicam2.setProperty("value", 11.8)
        self.AccuPicam2.setObjectName("AccuPicam2")
        self.gridLayout.addWidget(self.AccuPicam2, 10, 4, 1, 1)
        self.btn_gpio_A = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gpio_A.setObjectName("btn_gpio_A")
        self.gridLayout.addWidget(self.btn_gpio_A, 14, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.wind_dir = QtWidgets.QSpinBox(self.centralwidget)
        self.wind_dir.setEnabled(True)
        self.wind_dir.setMinimum(-90)
        self.wind_dir.setMaximum(90)
        self.wind_dir.setObjectName("wind_dir")
        self.gridLayout.addWidget(self.wind_dir, 2, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 3, 1, 1)
        self.listWBtn = QtWidgets.QListWidget(self.centralwidget)
        self.listWBtn.setMinimumSize(QtCore.QSize(300, 0))
        self.listWBtn.setObjectName("listWBtn")
        self.gridLayout.addWidget(self.listWBtn, 2, 2, 11, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.rainProcessing = QtWidgets.QCheckBox(self.centralwidget)
        self.rainProcessing.setObjectName("rainProcessing")
        self.gridLayout.addWidget(self.rainProcessing, 5, 5, 1, 1)
        self.rssi_picam1 = QtWidgets.QSpinBox(self.centralwidget)
        self.rssi_picam1.setEnabled(True)
        self.rssi_picam1.setMinimum(0)
        self.rssi_picam1.setMaximum(100)
        self.rssi_picam1.setProperty("value", 90)
        self.rssi_picam1.setObjectName("rssi_picam1")
        self.gridLayout.addWidget(self.rssi_picam1, 8, 4, 1, 1)
        self.wind_dirVoltage = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.wind_dirVoltage.setDecimals(1)
        self.wind_dirVoltage.setMinimum(9.0)
        self.wind_dirVoltage.setMaximum(12.6)
        self.wind_dirVoltage.setSingleStep(0.1)
        self.wind_dirVoltage.setProperty("value", 11.8)
        self.wind_dirVoltage.setObjectName("wind_dirVoltage")
        self.gridLayout.addWidget(self.wind_dirVoltage, 3, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 15))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.picam1Processing = QtWidgets.QCheckBox(self.centralwidget)
        self.picam1Processing.setObjectName("picam1Processing")
        self.gridLayout.addWidget(self.picam1Processing, 7, 5, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 11, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 3, 1, 3)
        self.btn_gpio_B = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gpio_B.setObjectName("btn_gpio_B")
        self.gridLayout.addWidget(self.btn_gpio_B, 14, 1, 1, 1)
        self.rssi_picam2 = QtWidgets.QSpinBox(self.centralwidget)
        self.rssi_picam2.setEnabled(True)
        self.rssi_picam2.setMinimum(0)
        self.rssi_picam2.setMaximum(100)
        self.rssi_picam2.setProperty("value", 95)
        self.rssi_picam2.setObjectName("rssi_picam2")
        self.gridLayout.addWidget(self.rssi_picam2, 11, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 3, 1, 1)
        self.listBaseB = QtWidgets.QListWidget(self.centralwidget)
        self.listBaseB.setMinimumSize(QtCore.QSize(100, 0))
        self.listBaseB.setObjectName("listBaseB")
        self.gridLayout.addWidget(self.listBaseB, 2, 1, 11, 1)
        self.dirProcessing = QtWidgets.QCheckBox(self.centralwidget)
        self.dirProcessing.setObjectName("dirProcessing")
        self.gridLayout.addWidget(self.dirProcessing, 2, 5, 2, 1)
        self.btn_send_Info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send_Info.setObjectName("btn_send_Info")
        self.gridLayout.addWidget(self.btn_send_Info, 14, 3, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chrono Simulate Bases"))
        self.label_28.setText(_translate("MainWindow", "Accu"))
        self.speedProcessing.setText(_translate("MainWindow", "Speed"))
        self.rain.setText(_translate("MainWindow", "Rain"))
        self.picam2Processing.setText(_translate("MainWindow", "Picam2"))
        self.label_26.setText(_translate("MainWindow", "RSSI"))
        self.label_25.setText(_translate("MainWindow", "Accu"))
        self.btn_gpio_A.setText(_translate("MainWindow", "GPIO Btn"))
        self.label_3.setText(_translate("MainWindow", "Base A"))
        self.label_13.setText(_translate("MainWindow", "Dir (°)"))
        self.label_5.setText(_translate("MainWindow", "Wireless btn"))
        self.rainProcessing.setText(_translate("MainWindow", "Rain"))
        self.label_12.setText(_translate("MainWindow", "Speed\n"
"(m/s)"))
        self.picam1Processing.setText(_translate("MainWindow", "Picam1"))
        self.label_4.setText(_translate("MainWindow", "Base B"))
        self.label_27.setText(_translate("MainWindow", "RSSI"))
        self.btn_gpio_B.setText(_translate("MainWindow", "GPIO Btn"))
        self.label_15.setText(_translate("MainWindow", "Dir Accu"))
        self.dirProcessing.setText(_translate("MainWindow", "Dir"))
        self.btn_send_Info.setText(_translate("MainWindow", "Send info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
