# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WChronoTraining.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WTraining(object):
    def setupUi(self, WTraining):
        WTraining.setObjectName("WTraining")
        WTraining.resize(428, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WTraining.sizePolicy().hasHeightForWidth())
        WTraining.setSizePolicy(sizePolicy)
        WTraining.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WTraining)
        self.horizontalLayout_3.setContentsMargins(3, 1, 3, 1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lapNumber = QtWidgets.QLabel(WTraining)
        self.lapNumber.setObjectName("lapNumber")
        self.verticalLayout.addWidget(self.lapNumber)
        self.runMin = QtWidgets.QLabel(WTraining)
        self.runMin.setObjectName("runMin")
        self.verticalLayout.addWidget(self.runMin)
        self.runMean = QtWidgets.QLabel(WTraining)
        self.runMean.setObjectName("runMean")
        self.verticalLayout.addWidget(self.runMean)
        self.runMax = QtWidgets.QLabel(WTraining)
        self.runMax.setObjectName("runMax")
        self.verticalLayout.addWidget(self.runMax)
        self.Status = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status.sizePolicy().hasHeightForWidth())
        self.Status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Status.setFont(font)
        self.Status.setScaledContents(False)
        self.Status.setAlignment(QtCore.Qt.AlignCenter)
        self.Status.setWordWrap(False)
        self.Status.setObjectName("Status")
        self.verticalLayout.addWidget(self.Status)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LapTimeLabel = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LapTimeLabel.sizePolicy().hasHeightForWidth())
        self.LapTimeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LapTimeLabel.setFont(font)
        self.LapTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LapTimeLabel.setObjectName("LapTimeLabel")
        self.verticalLayout_5.addWidget(self.LapTimeLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Lap1 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap1.sizePolicy().hasHeightForWidth())
        self.Lap1.setSizePolicy(sizePolicy)
        self.Lap1.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap1.setFont(font)
        self.Lap1.setObjectName("Lap1")
        self.verticalLayout_4.addWidget(self.Lap1)
        self.Lap3 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap3.sizePolicy().hasHeightForWidth())
        self.Lap3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap3.setFont(font)
        self.Lap3.setObjectName("Lap3")
        self.verticalLayout_4.addWidget(self.Lap3)
        self.Lap5 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap5.sizePolicy().hasHeightForWidth())
        self.Lap5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap5.setFont(font)
        self.Lap5.setObjectName("Lap5")
        self.verticalLayout_4.addWidget(self.Lap5)
        self.Lap7 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap7.sizePolicy().hasHeightForWidth())
        self.Lap7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap7.setFont(font)
        self.Lap7.setObjectName("Lap7")
        self.verticalLayout_4.addWidget(self.Lap7)
        self.Lap9 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap9.sizePolicy().hasHeightForWidth())
        self.Lap9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap9.setFont(font)
        self.Lap9.setObjectName("Lap9")
        self.verticalLayout_4.addWidget(self.Lap9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Lap2 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap2.sizePolicy().hasHeightForWidth())
        self.Lap2.setSizePolicy(sizePolicy)
        self.Lap2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap2.setFont(font)
        self.Lap2.setObjectName("Lap2")
        self.verticalLayout_3.addWidget(self.Lap2)
        self.Lap4 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap4.sizePolicy().hasHeightForWidth())
        self.Lap4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap4.setFont(font)
        self.Lap4.setObjectName("Lap4")
        self.verticalLayout_3.addWidget(self.Lap4)
        self.Lap6 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap6.sizePolicy().hasHeightForWidth())
        self.Lap6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap6.setFont(font)
        self.Lap6.setObjectName("Lap6")
        self.verticalLayout_3.addWidget(self.Lap6)
        self.Lap8 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap8.sizePolicy().hasHeightForWidth())
        self.Lap8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap8.setFont(font)
        self.Lap8.setObjectName("Lap8")
        self.verticalLayout_3.addWidget(self.Lap8)
        self.Lap10 = QtWidgets.QLabel(WTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lap10.sizePolicy().hasHeightForWidth())
        self.Lap10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lap10.setFont(font)
        self.Lap10.setObjectName("Lap10")
        self.verticalLayout_3.addWidget(self.Lap10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)

        self.retranslateUi(WTraining)
        QtCore.QMetaObject.connectSlotsByName(WTraining)

    def retranslateUi(self, WTraining):
        _translate = QtCore.QCoreApplication.translate
        WTraining.setWindowTitle(_translate("WTraining", "Form"))
        self.lapNumber.setText(_translate("WTraining", "Lap Number : 0"))
        self.runMin.setText(_translate("WTraining", "Min : "))
        self.runMean.setText(_translate("WTraining", "Mean : "))
        self.runMax.setText(_translate("WTraining", "Max : "))
        self.Status.setText(_translate("WTraining", "Wait New Run"))
        self.LapTimeLabel.setText(_translate("WTraining", "Run(s) Time (s)"))
        self.Lap1.setText(_translate("WTraining", "1 : XX.XXX"))
        self.Lap3.setText(_translate("WTraining", "3 : XX.XXX"))
        self.Lap5.setText(_translate("WTraining", "5 : XX.XXX"))
        self.Lap7.setText(_translate("WTraining", "7 : XX.XXX"))
        self.Lap9.setText(_translate("WTraining", "9 : XX.XXX"))
        self.Lap2.setText(_translate("WTraining", "2 : XX.XXX"))
        self.Lap4.setText(_translate("WTraining", "4 : XX.XXX"))
        self.Lap6.setText(_translate("WTraining", "6 : XX.XXX"))
        self.Lap8.setText(_translate("WTraining", "8 : XX.XXX"))
        self.Lap10.setText(_translate("WTraining", "10 : XX.XXX"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WTraining = QtWidgets.QWidget()
    ui = Ui_WTraining()
    ui.setupUi(WTraining)
    WTraining.show()
    sys.exit(app.exec_())
