# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WConfig.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WConfig(object):
    def setupUi(self, WConfig):
        WConfig.setObjectName("WConfig")
        WConfig.resize(480, 254)
        self.gridLayout = QtWidgets.QGridLayout(WConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ChronoLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChronoLabel.setFont(font)
        self.ChronoLabel.setObjectName("ChronoLabel")
        self.horizontalLayout.addWidget(self.ChronoLabel)
        self.ChronoType = QtWidgets.QComboBox(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChronoType.setFont(font)
        self.ChronoType.setObjectName("ChronoType")
        self.ChronoType.addItem("")
        self.ChronoType.addItem("")
        self.ChronoType.addItem("")
        self.horizontalLayout.addWidget(self.ChronoType)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Contest = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Contest.setFont(font)
        self.Contest.setObjectName("Contest")
        self.horizontalLayout_2.addWidget(self.Contest)
        self.ContestList = QtWidgets.QComboBox(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ContestList.setFont(font)
        self.ContestList.setObjectName("ContestList")
        self.ContestList.addItem("")
        self.horizontalLayout_2.addWidget(self.ContestList)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.WireChronoLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WireChronoLabel.setFont(font)
        self.WireChronoLabel.setObjectName("WireChronoLabel")
        self.horizontalLayout_4.addWidget(self.WireChronoLabel)
        self.WireChronoValue = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WireChronoValue.setFont(font)
        self.WireChronoValue.setObjectName("WireChronoValue")
        self.horizontalLayout_4.addWidget(self.WireChronoValue)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PICamA_Btn = QtWidgets.QPushButton(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PICamA_Btn.setFont(font)
        self.PICamA_Btn.setObjectName("PICamA_Btn")
        self.horizontalLayout_5.addWidget(self.PICamA_Btn)
        self.PICamA_Value = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PICamA_Value.setFont(font)
        self.PICamA_Value.setObjectName("PICamA_Value")
        self.horizontalLayout_5.addWidget(self.PICamA_Value)
        self.PICamB_Btn = QtWidgets.QPushButton(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PICamB_Btn.setFont(font)
        self.PICamB_Btn.setObjectName("PICamB_Btn")
        self.horizontalLayout_5.addWidget(self.PICamB_Btn)
        self.PICamB_Value = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PICamB_Value.setFont(font)
        self.PICamB_Value.setObjectName("PICamB_Value")
        self.horizontalLayout_5.addWidget(self.PICamB_Value)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.ContestLimitLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ContestLimitLabel.setFont(font)
        self.ContestLimitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ContestLimitLabel.setObjectName("ContestLimitLabel")
        self.verticalLayout.addWidget(self.ContestLimitLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.WindMinLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WindMinLabel.setFont(font)
        self.WindMinLabel.setObjectName("WindMinLabel")
        self.horizontalLayout_7.addWidget(self.WindMinLabel)
        self.WindMinValue = QtWidgets.QSpinBox(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WindMinValue.setFont(font)
        self.WindMinValue.setObjectName("WindMinValue")
        self.horizontalLayout_7.addWidget(self.WindMinValue)
        self.WindMaxLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WindMaxLabel.setFont(font)
        self.WindMaxLabel.setObjectName("WindMaxLabel")
        self.horizontalLayout_7.addWidget(self.WindMaxLabel)
        self.WindMaxValue = QtWidgets.QSpinBox(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WindMaxValue.setFont(font)
        self.WindMaxValue.setObjectName("WindMaxValue")
        self.horizontalLayout_7.addWidget(self.WindMaxValue)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.OrientationLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OrientationLabel.setFont(font)
        self.OrientationLabel.setObjectName("OrientationLabel")
        self.horizontalLayout_9.addWidget(self.OrientationLabel)
        self.OrientationValue = QtWidgets.QSpinBox(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OrientationValue.setFont(font)
        self.OrientationValue.setObjectName("OrientationValue")
        self.horizontalLayout_9.addWidget(self.OrientationValue)
        self.RevolLabel = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RevolLabel.setFont(font)
        self.RevolLabel.setObjectName("RevolLabel")
        self.horizontalLayout_9.addWidget(self.RevolLabel)
        self.RevolValue = QtWidgets.QSpinBox(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RevolValue.setFont(font)
        self.RevolValue.setObjectName("RevolValue")
        self.horizontalLayout_9.addWidget(self.RevolValue)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.StartBtn = QtWidgets.QPushButton(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.verticalLayout.addWidget(self.StartBtn)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(WConfig)
        QtCore.QMetaObject.connectSlotsByName(WConfig)

    def retranslateUi(self, WConfig):
        _translate = QtCore.QCoreApplication.translate
        WConfig.setWindowTitle(_translate("WConfig", "Form"))
        self.ChronoLabel.setText(_translate("WConfig", "Chrono type"))
        self.ChronoType.setItemText(0, _translate("WConfig", "Wire Chrono"))
        self.ChronoType.setItemText(1, _translate("WConfig", "Wireless Chrono"))
        self.ChronoType.setItemText(2, _translate("WConfig", "Test"))
        self.Contest.setText(_translate("WConfig", "Contest"))
        self.ContestList.setItemText(0, _translate("WConfig", "None"))
        self.WireChronoLabel.setText(_translate("WConfig", "Wire Chrono"))
        self.WireChronoValue.setText(_translate("WConfig", "XXs"))
        self.PICamA_Btn.setText(_translate("WConfig", "PICAM A"))
        self.PICamA_Value.setText(_translate("WConfig", "XXX.XXX.XXX.XXX"))
        self.PICamB_Btn.setText(_translate("WConfig", "PICAM B"))
        self.PICamB_Value.setText(_translate("WConfig", "XXX.XXX.XXX.XXX"))
        self.ContestLimitLabel.setText(_translate("WConfig", "Contest Limits"))
        self.WindMinLabel.setText(_translate("WConfig", "WindMin"))
        self.WindMaxLabel.setText(_translate("WConfig", "WindMax"))
        self.OrientationLabel.setText(_translate("WConfig", "Orientation"))
        self.RevolLabel.setText(_translate("WConfig", "Revol"))
        self.StartBtn.setText(_translate("WConfig", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WConfig = QtWidgets.QWidget()
    ui = Ui_WConfig()
    ui.setupUi(WConfig)
    WConfig.show()
    sys.exit(app.exec_())

