# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettingsAdvanced.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WConfig(object):
    def setupUi(self, WConfig):
        WConfig.setObjectName("WConfig")
        WConfig.resize(480, 268)
        self.gridLayout = QtWidgets.QGridLayout(WConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(WConfig)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_baseB = QtWidgets.QSpinBox(WConfig)
        self.btn_baseB.setObjectName("btn_baseB")
        self.horizontalLayout_6.addWidget(self.btn_baseB)
        self.label_4 = QtWidgets.QLabel(WConfig)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.buzzer = QtWidgets.QSpinBox(WConfig)
        self.buzzer.setObjectName("buzzer")
        self.horizontalLayout_9.addWidget(self.buzzer)
        self.label_7 = QtWidgets.QLabel(WConfig)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.udp_port = QtWidgets.QSpinBox(WConfig)
        self.udp_port.setObjectName("udp_port")
        self.horizontalLayout_10.addWidget(self.udp_port)
        self.label_8 = QtWidgets.QLabel(WConfig)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.buzzer_next = QtWidgets.QSpinBox(WConfig)
        self.buzzer_next.setObjectName("buzzer_next")
        self.horizontalLayout_8.addWidget(self.buzzer_next)
        self.label_6 = QtWidgets.QLabel(WConfig)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_baseA = QtWidgets.QSpinBox(WConfig)
        self.btn_baseA.setObjectName("btn_baseA")
        self.horizontalLayout_4.addWidget(self.btn_baseA)
        self.label_2 = QtWidgets.QLabel(WConfig)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_next = QtWidgets.QSpinBox(WConfig)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_7.addWidget(self.btn_next)
        self.label_5 = QtWidgets.QLabel(WConfig)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ledA = QtWidgets.QSpinBox(WConfig)
        self.ledA.setObjectName("ledA")
        self.horizontalLayout_11.addWidget(self.ledA)
        self.label_9 = QtWidgets.QLabel(WConfig)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ledB = QtWidgets.QSpinBox(WConfig)
        self.ledB.setObjectName("ledB")
        self.horizontalLayout_12.addWidget(self.ledB)
        self.label_10 = QtWidgets.QLabel(WConfig)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartBtn = QtWidgets.QPushButton(WConfig)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayout.addWidget(self.StartBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(WConfig)
        QtCore.QMetaObject.connectSlotsByName(WConfig)
        WConfig.setTabOrder(self.buzzer, self.buzzer_next)
        WConfig.setTabOrder(self.buzzer_next, self.ledA)
        WConfig.setTabOrder(self.ledA, self.ledB)
        WConfig.setTabOrder(self.ledB, self.btn_next)
        WConfig.setTabOrder(self.btn_next, self.btn_baseA)
        WConfig.setTabOrder(self.btn_baseA, self.udp_port)
        WConfig.setTabOrder(self.udp_port, self.btn_baseB)
        WConfig.setTabOrder(self.btn_baseB, self.StartBtn)
        WConfig.setTabOrder(self.StartBtn, WConfig.pushButton_4)
        WConfig.setTabOrder(WConfig.pushButton_4, WConfig.radioButton_6)
        WConfig.setTabOrder(WConfig.radioButton_6, WConfig.radioButton_7)
        WConfig.setTabOrder(WConfig.radioButton_7, WConfig.pushButton_5)
        WConfig.setTabOrder(WConfig.pushButton_5, WConfig.radioButton_8)
        WConfig.setTabOrder(WConfig.radioButton_8, WConfig.spinBox_2)
        WConfig.setTabOrder(WConfig.spinBox_2, WConfig.radioButton_4)

    def retranslateUi(self, WConfig):
        _translate = QtCore.QCoreApplication.translate
        WConfig.setWindowTitle(_translate("WConfig", "Form"))
        self.label.setText(_translate("WConfig", "Advanced Settings"))
        self.label_4.setText(_translate("WConfig", "Button Base B"))
        self.label_7.setText(_translate("WConfig", "Buzzer"))
        self.label_8.setText(_translate("WConfig", "UDP Port"))
        self.label_6.setText(_translate("WConfig", "Buzzer Next"))
        self.label_2.setText(_translate("WConfig", "Button Base A"))
        self.label_5.setText(_translate("WConfig", "Button Next"))
        self.label_9.setText(_translate("WConfig", "Led A"))
        self.label_10.setText(_translate("WConfig", "Led B"))
        self.StartBtn.setText(_translate("WConfig", "Back to Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WConfig = QtWidgets.QWidget()
    ui = Ui_WConfig()
    ui.setupUi(WConfig)
    WConfig.show()
    sys.exit(app.exec_())
