# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettingsBase.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsBase(object):
    def setupUi(self, WSettingsBase):
        WSettingsBase.setObjectName("WSettingsBase")
        WSettingsBase.resize(480, 271)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WSettingsBase.sizePolicy().hasHeightForWidth())
        WSettingsBase.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(WSettingsBase)
        self.gridLayout.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(WSettingsBase)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wbase_detect_btn = QtWidgets.QPushButton(WSettingsBase)
        self.wbase_detect_btn.setObjectName("wbase_detect_btn")
        self.gridLayout_2.addWidget(self.wbase_detect_btn, 0, 0, 1, 1)
        self.baseB_label = QtWidgets.QLabel(WSettingsBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseB_label.sizePolicy().hasHeightForWidth())
        self.baseB_label.setSizePolicy(sizePolicy)
        self.baseB_label.setMinimumSize(QtCore.QSize(2, 0))
        self.baseB_label.setObjectName("baseB_label")
        self.gridLayout_2.addWidget(self.baseB_label, 1, 1, 1, 1)
        self.buttonClearB = QtWidgets.QPushButton(WSettingsBase)
        self.buttonClearB.setObjectName("buttonClearB")
        self.gridLayout_2.addWidget(self.buttonClearB, 3, 1, 1, 1)
        self.buttonClearA = QtWidgets.QPushButton(WSettingsBase)
        self.buttonClearA.setObjectName("buttonClearA")
        self.gridLayout_2.addWidget(self.buttonClearA, 3, 0, 1, 1)
        self.baseA_label = QtWidgets.QLabel(WSettingsBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseA_label.sizePolicy().hasHeightForWidth())
        self.baseA_label.setSizePolicy(sizePolicy)
        self.baseA_label.setMinimumSize(QtCore.QSize(2, 0))
        self.baseA_label.setObjectName("baseA_label")
        self.gridLayout_2.addWidget(self.baseA_label, 1, 0, 1, 1)
        self.wbase_detect_btn_2 = QtWidgets.QPushButton(WSettingsBase)
        self.wbase_detect_btn_2.setObjectName("wbase_detect_btn_2")
        self.gridLayout_2.addWidget(self.wbase_detect_btn_2, 0, 1, 1, 1)
        self.listWidget_baseB = QtWidgets.QListWidget(WSettingsBase)
        self.listWidget_baseB.setObjectName("listWidget_baseB")
        self.gridLayout_2.addWidget(self.listWidget_baseB, 2, 1, 1, 1)
        self.listWidget_baseA = QtWidgets.QListWidget(WSettingsBase)
        self.listWidget_baseA.setObjectName("listWidget_baseA")
        self.gridLayout_2.addWidget(self.listWidget_baseA, 2, 0, 1, 1)
        self.buttonInvert = QtWidgets.QPushButton(WSettingsBase)
        self.buttonInvert.setObjectName("buttonInvert")
        self.gridLayout_2.addWidget(self.buttonInvert, 4, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(WSettingsBase)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_cancel = QtWidgets.QPushButton(WSettingsBase)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_valid = QtWidgets.QPushButton(WSettingsBase)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.horizontalLayout.addWidget(self.btn_valid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(WSettingsBase)
        QtCore.QMetaObject.connectSlotsByName(WSettingsBase)
        WSettingsBase.setTabOrder(self.btn_back, self.btn_cancel)
        WSettingsBase.setTabOrder(self.btn_cancel, self.btn_valid)

    def retranslateUi(self, WSettingsBase):
        _translate = QtCore.QCoreApplication.translate
        WSettingsBase.setWindowTitle(_translate("WSettingsBase", "Form"))
        self.label.setText(_translate("WSettingsBase", "Base Settings"))
        self.wbase_detect_btn.setText(_translate("WSettingsBase", "Detect"))
        self.baseB_label.setText(_translate("WSettingsBase", "Base B : "))
        self.buttonClearB.setText(_translate("WSettingsBase", "Clear"))
        self.buttonClearA.setText(_translate("WSettingsBase", "Clear"))
        self.baseA_label.setText(_translate("WSettingsBase", "Base A : "))
        self.wbase_detect_btn_2.setText(_translate("WSettingsBase", "Detect"))
        self.buttonInvert.setText(_translate("WSettingsBase", "Invert"))
        self.btn_back.setText(_translate("WSettingsBase", "Back to Settings"))
        self.btn_cancel.setText(_translate("WSettingsBase", "Cancel"))
        self.btn_valid.setText(_translate("WSettingsBase", "Valid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettingsBase = QtWidgets.QWidget()
    ui = Ui_WSettingsBase()
    ui.setupUi(WSettingsBase)
    WSettingsBase.show()
    sys.exit(app.exec_())
