# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettings(object):
    def setupUi(self, WSettings):
        WSettings.setObjectName("WSettings")
        WSettings.resize(480, 268)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WSettings.sizePolicy().hasHeightForWidth())
        WSettings.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(WSettings)
        self.gridLayout.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(WSettings)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.voice = QtWidgets.QCheckBox(WSettings)
        self.voice.setObjectName("voice")
        self.horizontalLayout_5.addWidget(self.voice)
        self.sound = QtWidgets.QCheckBox(WSettings)
        self.sound.setObjectName("sound")
        self.horizontalLayout_5.addWidget(self.sound)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.picamB = QtWidgets.QLineEdit(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picamB.sizePolicy().hasHeightForWidth())
        self.picamB.setSizePolicy(sizePolicy)
        self.picamB.setMinimumSize(QtCore.QSize(0, 0))
        self.picamB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.picamB.setObjectName("picamB")
        self.horizontalLayout_6.addWidget(self.picamB)
        self.label_4 = QtWidgets.QLabel(WSettings)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.voltagemin = QtWidgets.QDoubleSpinBox(WSettings)
        self.voltagemin.setDecimals(1)
        self.voltagemin.setSingleStep(0.1)
        self.voltagemin.setObjectName("voltagemin")
        self.horizontalLayout_4.addWidget(self.voltagemin)
        self.label_2 = QtWidgets.QLabel(WSettings)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.btn_invertpicam = QtWidgets.QPushButton(WSettings)
        self.btn_invertpicam.setObjectName("btn_invertpicam")
        self.gridLayout_2.addWidget(self.btn_invertpicam, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.picamA = QtWidgets.QLineEdit(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picamA.sizePolicy().hasHeightForWidth())
        self.picamA.setSizePolicy(sizePolicy)
        self.picamA.setMinimumSize(QtCore.QSize(0, 0))
        self.picamA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.picamA.setObjectName("picamA")
        self.horizontalLayout_7.addWidget(self.picamA)
        self.label_5 = QtWidgets.QLabel(WSettings)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.btn_invert_bases = QtWidgets.QPushButton(WSettings)
        self.btn_invert_bases.setObjectName("btn_invert_bases")
        self.gridLayout_2.addWidget(self.btn_invert_bases, 4, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.baseA = QtWidgets.QLineEdit(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseA.sizePolicy().hasHeightForWidth())
        self.baseA.setSizePolicy(sizePolicy)
        self.baseA.setMinimumSize(QtCore.QSize(0, 0))
        self.baseA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.baseA.setObjectName("baseA")
        self.horizontalLayout_8.addWidget(self.baseA)
        self.label_6 = QtWidgets.QLabel(WSettings)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.baseB = QtWidgets.QLineEdit(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseB.sizePolicy().hasHeightForWidth())
        self.baseB.setSizePolicy(sizePolicy)
        self.baseB.setMinimumSize(QtCore.QSize(0, 0))
        self.baseB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.baseB.setObjectName("baseB")
        self.horizontalLayout_9.addWidget(self.baseB)
        self.label_7 = QtWidgets.QLabel(WSettings)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 6, 1, 1, 1)
        self.anemometer = QtWidgets.QCheckBox(WSettings)
        self.anemometer.setObjectName("anemometer")
        self.gridLayout_2.addWidget(self.anemometer, 2, 1, 1, 1)
        self.arduino = QtWidgets.QCheckBox(WSettings)
        self.arduino.setObjectName("arduino")
        self.gridLayout_2.addWidget(self.arduino, 2, 0, 1, 1)
        self.simulate_mode = QtWidgets.QCheckBox(WSettings)
        self.simulate_mode.setObjectName("simulate_mode")
        self.gridLayout_2.addWidget(self.simulate_mode, 1, 0, 1, 1)
        self.fullscreen = QtWidgets.QCheckBox(WSettings)
        self.fullscreen.setObjectName("fullscreen")
        self.gridLayout_2.addWidget(self.fullscreen, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_advanced_settings = QtWidgets.QPushButton(WSettings)
        self.btn_advanced_settings.setObjectName("btn_advanced_settings")
        self.horizontalLayout.addWidget(self.btn_advanced_settings)
        self.btn_cancel = QtWidgets.QPushButton(WSettings)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_valid = QtWidgets.QPushButton(WSettings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.horizontalLayout.addWidget(self.btn_valid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(WSettings)
        QtCore.QMetaObject.connectSlotsByName(WSettings)
        WSettings.setTabOrder(self.arduino, self.anemometer)
        WSettings.setTabOrder(self.anemometer, self.voltagemin)
        WSettings.setTabOrder(self.voltagemin, self.btn_invertpicam)
        WSettings.setTabOrder(self.btn_invertpicam, self.btn_invert_bases)
        WSettings.setTabOrder(self.btn_invert_bases, self.picamA)
        WSettings.setTabOrder(self.picamA, self.baseA)
        WSettings.setTabOrder(self.baseA, self.picamB)
        WSettings.setTabOrder(self.picamB, self.baseB)
        WSettings.setTabOrder(self.baseB, self.btn_advanced_settings)
        WSettings.setTabOrder(self.btn_advanced_settings, self.btn_cancel)
        WSettings.setTabOrder(self.btn_cancel, self.btn_valid)

    def retranslateUi(self, WSettings):
        _translate = QtCore.QCoreApplication.translate
        WSettings.setWindowTitle(_translate("WSettings", "Form"))
        self.label.setText(_translate("WSettings", "Settings"))
        self.voice.setText(_translate("WSettings", "Voice"))
        self.sound.setText(_translate("WSettings", "Sound"))
        self.picamB.setText(_translate("WSettings", "192.168.0.16"))
        self.label_4.setText(_translate("WSettings", "piCamB"))
        self.label_2.setText(_translate("WSettings", "Min Voltage"))
        self.btn_invertpicam.setText(_translate("WSettings", "Invert piCam"))
        self.picamA.setText(_translate("WSettings", "192.168.0.17"))
        self.label_5.setText(_translate("WSettings", "piCamA"))
        self.btn_invert_bases.setText(_translate("WSettings", "Invert Buttons"))
        self.baseA.setText(_translate("WSettings", "Port 17"))
        self.label_6.setText(_translate("WSettings", "BaseA"))
        self.baseB.setText(_translate("WSettings", "Port 18"))
        self.label_7.setText(_translate("WSettings", "BaseB"))
        self.anemometer.setText(_translate("WSettings", "Anemometer"))
        self.arduino.setText(_translate("WSettings", "ArduinoChrono"))
        self.simulate_mode.setText(_translate("WSettings", "Simulate Mode"))
        self.fullscreen.setText(_translate("WSettings", "FullScreen"))
        self.btn_advanced_settings.setText(_translate("WSettings", "Advanced Settings"))
        self.btn_cancel.setText(_translate("WSettings", "Cancel"))
        self.btn_valid.setText(_translate("WSettings", "Valid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettings = QtWidgets.QWidget()
    ui = Ui_WSettings()
    ui.setupUi(WSettings)
    WSettings.show()
    sys.exit(app.exec_())
