# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettings(object):
    def setupUi(self, WSettings):
        WSettings.setObjectName("WSettings")
        WSettings.resize(480, 271)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WSettings.sizePolicy().hasHeightForWidth())
        WSettings.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(WSettings)
        self.gridLayout.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(WSettings)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fullscreen = QtWidgets.QCheckBox(WSettings)
        self.fullscreen.setObjectName("fullscreen")
        self.gridLayout_2.addWidget(self.fullscreen, 2, 1, 1, 1)
        self.arduino = QtWidgets.QCheckBox(WSettings)
        self.arduino.setObjectName("arduino")
        self.gridLayout_2.addWidget(self.arduino, 3, 0, 1, 1)
        self.simulate_mode = QtWidgets.QCheckBox(WSettings)
        self.simulate_mode.setObjectName("simulate_mode")
        self.gridLayout_2.addWidget(self.simulate_mode, 2, 0, 1, 1)
        self.anemometer = QtWidgets.QCheckBox(WSettings)
        self.anemometer.setObjectName("anemometer")
        self.gridLayout_2.addWidget(self.anemometer, 3, 1, 1, 1)
        self.voice = QtWidgets.QCheckBox(WSettings)
        self.voice.setObjectName("voice")
        self.gridLayout_2.addWidget(self.voice, 4, 1, 1, 1)
        self.sound = QtWidgets.QCheckBox(WSettings)
        self.sound.setObjectName("sound")
        self.gridLayout_2.addWidget(self.sound, 4, 0, 1, 1)
        self.buzzer = QtWidgets.QCheckBox(WSettings)
        self.buzzer.setObjectName("buzzer")
        self.gridLayout_2.addWidget(self.buzzer, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.voltagemin = QtWidgets.QDoubleSpinBox(WSettings)
        self.voltagemin.setDecimals(1)
        self.voltagemin.setSingleStep(0.1)
        self.voltagemin.setObjectName("voltagemin")
        self.horizontalLayout_4.addWidget(self.voltagemin)
        self.label_2 = QtWidgets.QLabel(WSettings)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.buzzernext = QtWidgets.QCheckBox(WSettings)
        self.buzzernext.setObjectName("buzzernext")
        self.gridLayout_2.addWidget(self.buzzernext, 5, 1, 1, 1)
        self.closebtn = QtWidgets.QPushButton(WSettings)
        self.closebtn.setObjectName("closebtn")
        self.gridLayout_2.addWidget(self.closebtn, 7, 1, 1, 1)
        self.webserver = QtWidgets.QCheckBox(WSettings)
        self.webserver.setObjectName("webserver")
        self.gridLayout_2.addWidget(self.webserver, 6, 0, 1, 1)
        self.webserverUrl = QtWidgets.QLabel(WSettings)
        self.webserverUrl.setObjectName("webserverUrl")
        self.gridLayout_2.addWidget(self.webserverUrl, 6, 1, 1, 1)
        self.wbase_detect_btn = QtWidgets.QPushButton(WSettings)
        self.wbase_detect_btn.setObjectName("wbase_detect_btn")
        self.gridLayout_2.addWidget(self.wbase_detect_btn, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.baseA_label = QtWidgets.QLabel(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseA_label.sizePolicy().hasHeightForWidth())
        self.baseA_label.setSizePolicy(sizePolicy)
        self.baseA_label.setMinimumSize(QtCore.QSize(2, 0))
        self.baseA_label.setObjectName("baseA_label")
        self.horizontalLayout_5.addWidget(self.baseA_label)
        self.baseA_IP = QtWidgets.QTextEdit(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseA_IP.sizePolicy().hasHeightForWidth())
        self.baseA_IP.setSizePolicy(sizePolicy)
        self.baseA_IP.setMinimumSize(QtCore.QSize(0, 22))
        self.baseA_IP.setFrameShape(QtWidgets.QFrame.Panel)
        self.baseA_IP.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.baseA_IP.setObjectName("baseA_IP")
        self.horizontalLayout_5.addWidget(self.baseA_IP)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.baseB_label = QtWidgets.QLabel(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseB_label.sizePolicy().hasHeightForWidth())
        self.baseB_label.setSizePolicy(sizePolicy)
        self.baseB_label.setMinimumSize(QtCore.QSize(2, 0))
        self.baseB_label.setObjectName("baseB_label")
        self.horizontalLayout_3.addWidget(self.baseB_label)
        self.baseB_IP = QtWidgets.QTextEdit(WSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseB_IP.sizePolicy().hasHeightForWidth())
        self.baseB_IP.setSizePolicy(sizePolicy)
        self.baseB_IP.setMinimumSize(QtCore.QSize(0, 22))
        self.baseB_IP.setFrameShape(QtWidgets.QFrame.Panel)
        self.baseB_IP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.baseB_IP.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.baseB_IP.setObjectName("baseB_IP")
        self.horizontalLayout_3.addWidget(self.baseB_IP)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.wbase_invert_btn = QtWidgets.QPushButton(WSettings)
        self.wbase_invert_btn.setObjectName("wbase_invert_btn")
        self.gridLayout_2.addWidget(self.wbase_invert_btn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_advanced_settings = QtWidgets.QPushButton(WSettings)
        self.btn_advanced_settings.setObjectName("btn_advanced_settings")
        self.horizontalLayout.addWidget(self.btn_advanced_settings)
        self.btn_cancel = QtWidgets.QPushButton(WSettings)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_valid = QtWidgets.QPushButton(WSettings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.horizontalLayout.addWidget(self.btn_valid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(WSettings)
        QtCore.QMetaObject.connectSlotsByName(WSettings)
        WSettings.setTabOrder(self.arduino, self.anemometer)
        WSettings.setTabOrder(self.anemometer, self.voltagemin)
        WSettings.setTabOrder(self.voltagemin, self.btn_advanced_settings)
        WSettings.setTabOrder(self.btn_advanced_settings, self.btn_cancel)
        WSettings.setTabOrder(self.btn_cancel, self.btn_valid)

    def retranslateUi(self, WSettings):
        _translate = QtCore.QCoreApplication.translate
        WSettings.setWindowTitle(_translate("WSettings", "Form"))
        self.label.setText(_translate("WSettings", "Settings"))
        self.fullscreen.setText(_translate("WSettings", "FullScreen"))
        self.arduino.setText(_translate("WSettings", "ArduinoChrono"))
        self.simulate_mode.setText(_translate("WSettings", "Simulate Mode"))
        self.anemometer.setText(_translate("WSettings", "Anemometer"))
        self.voice.setText(_translate("WSettings", "Voice"))
        self.sound.setText(_translate("WSettings", "Sound"))
        self.buzzer.setText(_translate("WSettings", "Buzzer"))
        self.label_2.setText(_translate("WSettings", "Min Voltage"))
        self.buzzernext.setText(_translate("WSettings", "Buzzer Next button"))
        self.closebtn.setText(_translate("WSettings", "Close Race Management"))
        self.webserver.setText(_translate("WSettings", "WebServer"))
        self.webserverUrl.setText(_translate("WSettings", "Not started"))
        self.wbase_detect_btn.setText(_translate("WSettings", "Wireless bases detect"))
        self.baseA_label.setText(_translate("WSettings", "Base A : "))
        self.baseA_IP.setHtml(_translate("WSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">None</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.baseB_label.setText(_translate("WSettings", "Base B : "))
        self.baseB_IP.setHtml(_translate("WSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">None</p></body></html>"))
        self.wbase_invert_btn.setText(_translate("WSettings", "Wireless bases invert"))
        self.btn_advanced_settings.setText(_translate("WSettings", "Advanced Settings"))
        self.btn_cancel.setText(_translate("WSettings", "Cancel"))
        self.btn_valid.setText(_translate("WSettings", "Valid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettings = QtWidgets.QWidget()
    ui = Ui_WSettings()
    ui.setupUi(WSettings)
    WSettings.show()
    sys.exit(app.exec_())
