# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettingsSound.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsSound(object):
    def setupUi(self, WSettingsSound):
        WSettingsSound.setObjectName("WSettingsSound")
        WSettingsSound.resize(456, 239)
        self.gridLayout = QtWidgets.QGridLayout(WSettingsSound)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.sound = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sound.setFont(font)
        self.sound.setObjectName("sound")
        self.gridLayout.addWidget(self.sound, 2, 0, 1, 1)
        self.btn_valid = QtWidgets.QPushButton(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.gridLayout.addWidget(self.btn_valid, 7, 2, 1, 2)
        self.WeatherStationAlarmSound = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherStationAlarmSound.setFont(font)
        self.WeatherStationAlarmSound.setObjectName("WeatherStationAlarmSound")
        self.gridLayout.addWidget(self.WeatherStationAlarmSound, 6, 1, 1, 2)
        self.btn_cancel = QtWidgets.QPushButton(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 7, 1, 1, 1)
        self.soundslider = QtWidgets.QSlider(WSettingsSound)
        self.soundslider.setMaximum(100)
        self.soundslider.setProperty("value", 100)
        self.soundslider.setTracking(True)
        self.soundslider.setOrientation(QtCore.Qt.Horizontal)
        self.soundslider.setInvertedAppearance(False)
        self.soundslider.setInvertedControls(False)
        self.soundslider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.soundslider.setTickInterval(10)
        self.soundslider.setObjectName("soundslider")
        self.gridLayout.addWidget(self.soundslider, 2, 2, 1, 2)
        self.line = QtWidgets.QFrame(WSettingsSound)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 3)
        self.noiseslider = QtWidgets.QSlider(WSettingsSound)
        self.noiseslider.setMaximum(100)
        self.noiseslider.setSliderPosition(5)
        self.noiseslider.setOrientation(QtCore.Qt.Horizontal)
        self.noiseslider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.noiseslider.setTickInterval(10)
        self.noiseslider.setObjectName("noiseslider")
        self.gridLayout.addWidget(self.noiseslider, 3, 2, 1, 1)
        self.noiseSound = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noiseSound.setFont(font)
        self.noiseSound.setObjectName("noiseSound")
        self.gridLayout.addWidget(self.noiseSound, 3, 0, 1, 1)
        self.buzzernext = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buzzernext.setFont(font)
        self.buzzernext.setObjectName("buzzernext")
        self.gridLayout.addWidget(self.buzzernext, 1, 0, 1, 1)
        self.btn_back = QtWidgets.QPushButton(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 7, 0, 1, 1)
        self.soundvolume = QtWidgets.QSpinBox(WSettingsSound)
        self.soundvolume.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.soundvolume.setFont(font)
        self.soundvolume.setMaximum(100)
        self.soundvolume.setProperty("value", 100)
        self.soundvolume.setObjectName("soundvolume")
        self.gridLayout.addWidget(self.soundvolume, 2, 1, 1, 1)
        self.noisevolume = QtWidgets.QDoubleSpinBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noisevolume.setFont(font)
        self.noisevolume.setDecimals(0)
        self.noisevolume.setMaximum(100.0)
        self.noisevolume.setSingleStep(1.0)
        self.noisevolume.setObjectName("noisevolume")
        self.gridLayout.addWidget(self.noisevolume, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.WeatherStationAlarmBuzzer = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherStationAlarmBuzzer.setFont(font)
        self.WeatherStationAlarmBuzzer.setObjectName("WeatherStationAlarmBuzzer")
        self.gridLayout.addWidget(self.WeatherStationAlarmBuzzer, 6, 0, 1, 1)

        self.retranslateUi(WSettingsSound)
        QtCore.QMetaObject.connectSlotsByName(WSettingsSound)

    def retranslateUi(self, WSettingsSound):
        _translate = QtCore.QCoreApplication.translate
        WSettingsSound.setWindowTitle(_translate("WSettingsSound", "Form"))
        self.sound.setText(_translate("WSettingsSound", "Sound (%)"))
        self.btn_valid.setText(_translate("WSettingsSound", "Valid"))
        self.WeatherStationAlarmSound.setText(_translate("WSettingsSound", "Alarm Sound"))
        self.btn_cancel.setText(_translate("WSettingsSound", "Cancel"))
        self.noiseSound.setText(_translate("WSettingsSound", "Noise Sound (%)"))
        self.buzzernext.setText(_translate("WSettingsSound", "Buzzer Next button"))
        self.btn_back.setText(_translate("WSettingsSound", "Back to Settings"))
        self.label.setText(_translate("WSettingsSound", "Sound Settings"))
        self.label_2.setText(_translate("WSettingsSound", "Weather Station"))
        self.WeatherStationAlarmBuzzer.setText(_translate("WSettingsSound", "Alarm Buzzer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettingsSound = QtWidgets.QWidget()
    ui = Ui_WSettingsSound()
    ui.setupUi(WSettingsSound)
    WSettingsSound.show()
    sys.exit(app.exec_())
