# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsConnectedDevices(object):
    def setupUi(self, WSettingsConnectedDevices):
        WSettingsConnectedDevices.setObjectName("WSettingsConnectedDevices")
        WSettingsConnectedDevices.resize(469, 253)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WSettingsConnectedDevices.sizePolicy().hasHeightForWidth())
        WSettingsConnectedDevices.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(WSettingsConnectedDevices)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_cancel = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.fullscreen = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fullscreen.setFont(font)
        self.fullscreen.setObjectName("fullscreen")
        self.gridLayout.addWidget(self.fullscreen, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.btn_advanced_settings = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_advanced_settings.setFont(font)
        self.btn_advanced_settings.setObjectName("btn_advanced_settings")
        self.gridLayout.addWidget(self.btn_advanced_settings, 7, 1, 1, 1)
        self.btn_sound_settings = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sound_settings.setFont(font)
        self.btn_sound_settings.setObjectName("btn_sound_settings")
        self.gridLayout.addWidget(self.btn_sound_settings, 6, 1, 1, 1)
        self.simulate_mode = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.simulate_mode.setFont(font)
        self.simulate_mode.setObjectName("simulate_mode")
        self.gridLayout.addWidget(self.simulate_mode, 4, 0, 1, 1)
        self.btn_wDevices_settings = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_wDevices_settings.setFont(font)
        self.btn_wDevices_settings.setObjectName("btn_wDevices_settings")
        self.gridLayout.addWidget(self.btn_wDevices_settings, 6, 0, 1, 1)
        self.btn_valid = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.gridLayout.addWidget(self.btn_valid, 8, 1, 1, 1)
        self.webserver = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.webserver.setFont(font)
        self.webserver.setObjectName("webserver")
        self.gridLayout.addWidget(self.webserver, 3, 1, 1, 1)
        self.language = QtWidgets.QComboBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.language.setFont(font)
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.gridLayout.addWidget(self.language, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.mode = QtWidgets.QComboBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mode.setFont(font)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.gridLayout.addWidget(self.mode, 2, 1, 1, 1)
        self.webserverUrl = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.webserverUrl.setFont(font)
        self.webserverUrl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.webserverUrl.setCheckable(False)
        self.webserverUrl.setObjectName("webserverUrl")
        self.gridLayout.addWidget(self.webserverUrl, 4, 1, 1, 1)

        self.retranslateUi(WSettingsConnectedDevices)
        self.mode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WSettingsConnectedDevices)

    def retranslateUi(self, WSettingsConnectedDevices):
        _translate = QtCore.QCoreApplication.translate
        WSettingsConnectedDevices.setWindowTitle(_translate("WSettingsConnectedDevices", "Form"))
        self.btn_cancel.setText(_translate("WSettingsConnectedDevices", "Cancel"))
        self.label.setText(_translate("WSettingsConnectedDevices", "Race Management Settings"))
        self.fullscreen.setText(_translate("WSettingsConnectedDevices", "FullScreen"))
        self.label_2.setText(_translate("WSettingsConnectedDevices", "Mode"))
        self.btn_advanced_settings.setText(_translate("WSettingsConnectedDevices", "Advanced Settings"))
        self.btn_sound_settings.setText(_translate("WSettingsConnectedDevices", "Sound && Voice Settings"))
        self.simulate_mode.setText(_translate("WSettingsConnectedDevices", "Simulate Mode"))
        self.btn_wDevices_settings.setText(_translate("WSettingsConnectedDevices", "Wireless Devices Settings"))
        self.btn_valid.setText(_translate("WSettingsConnectedDevices", "Valid"))
        self.webserver.setText(_translate("WSettingsConnectedDevices", "WebServer"))
        self.language.setItemText(0, _translate("WSettingsConnectedDevices", "French"))
        self.language.setItemText(1, _translate("WSettingsConnectedDevices", "English"))
        self.label_3.setText(_translate("WSettingsConnectedDevices", "Langage"))
        self.mode.setItemText(0, _translate("WSettingsConnectedDevices", "Training"))
        self.mode.setItemText(1, _translate("WSettingsConnectedDevices", "Competition"))
        self.webserverUrl.setText(_translate("WSettingsConnectedDevices", "Not started"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettingsConnectedDevices = QtWidgets.QWidget()
    ui = Ui_WSettingsConnectedDevices()
    ui.setupUi(WSettingsConnectedDevices)
    WSettingsConnectedDevices.show()
    sys.exit(app.exec_())
