# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettingsSound.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsSound(object):
    def setupUi(self, WSettingsSound):
        WSettingsSound.setObjectName("WSettingsSound")
        WSettingsSound.resize(432, 236)
        self.gridLayout = QtWidgets.QGridLayout(WSettingsSound)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_cancel = QtWidgets.QPushButton(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.buzzernext = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buzzernext.setFont(font)
        self.buzzernext.setObjectName("buzzernext")
        self.gridLayout.addWidget(self.buzzernext, 4, 0, 1, 1)
        self.voice = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voice.setFont(font)
        self.voice.setObjectName("voice")
        self.gridLayout.addWidget(self.voice, 2, 0, 1, 1)
        self.sound = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sound.setFont(font)
        self.sound.setObjectName("sound")
        self.gridLayout.addWidget(self.sound, 1, 0, 1, 1)
        self.buzzer = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buzzer.setFont(font)
        self.buzzer.setObjectName("buzzer")
        self.gridLayout.addWidget(self.buzzer, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 5, 2, 1, 1)
        self.noiseSound = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noiseSound.setFont(font)
        self.noiseSound.setObjectName("noiseSound")
        self.gridLayout.addWidget(self.noiseSound, 5, 0, 1, 1)
        self.btn_back = QtWidgets.QPushButton(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 7, 0, 1, 1)
        self.noisevolume = QtWidgets.QDoubleSpinBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noisevolume.setFont(font)
        self.noisevolume.setDecimals(3)
        self.noisevolume.setSingleStep(0.001)
        self.noisevolume.setProperty("value", 0.005)
        self.noisevolume.setObjectName("noisevolume")
        self.gridLayout.addWidget(self.noisevolume, 5, 1, 1, 1)
        self.lowVoltage = QtWidgets.QCheckBox(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lowVoltage.setFont(font)
        self.lowVoltage.setObjectName("lowVoltage")
        self.gridLayout.addWidget(self.lowVoltage, 6, 0, 1, 1)
        self.btn_valid = QtWidgets.QPushButton(WSettingsSound)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.gridLayout.addWidget(self.btn_valid, 7, 2, 1, 1)

        self.retranslateUi(WSettingsSound)
        QtCore.QMetaObject.connectSlotsByName(WSettingsSound)

    def retranslateUi(self, WSettingsSound):
        _translate = QtCore.QCoreApplication.translate
        WSettingsSound.setWindowTitle(_translate("WSettingsSound", "Form"))
        self.btn_cancel.setText(_translate("WSettingsSound", "Cancel"))
        self.label.setText(_translate("WSettingsSound", "Sound Settings"))
        self.buzzernext.setText(_translate("WSettingsSound", "Buzzer Next button"))
        self.voice.setText(_translate("WSettingsSound", "Voice"))
        self.sound.setText(_translate("WSettingsSound", "Sound"))
        self.buzzer.setText(_translate("WSettingsSound", "Buzzer"))
        self.label_22.setText(_translate("WSettingsSound", "Noise Volume"))
        self.noiseSound.setText(_translate("WSettingsSound", "Noise Sound"))
        self.btn_back.setText(_translate("WSettingsSound", "Back to Settings"))
        self.lowVoltage.setText(_translate("WSettingsSound", "Low Voltage"))
        self.btn_valid.setText(_translate("WSettingsSound", "Valid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettingsSound = QtWidgets.QWidget()
    ui = Ui_WSettingsSound()
    ui.setupUi(WSettingsSound)
    WSettingsSound.show()
    sys.exit(app.exec_())
