# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettingsAdvanced.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsAdvanced(object):
    def setupUi(self, WSettingsAdvanced):
        WSettingsAdvanced.setObjectName("WSettingsAdvanced")
        WSettingsAdvanced.resize(480, 273)
        self.gridLayout = QtWidgets.QGridLayout(WSettingsAdvanced)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.WeatherSensorLostTimeOut = QtWidgets.QSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherSensorLostTimeOut.setFont(font)
        self.WeatherSensorLostTimeOut.setObjectName("WeatherSensorLostTimeOut")
        self.gridLayout.addWidget(self.WeatherSensorLostTimeOut, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 3, 1, 1)
        self.voltagecoef_2 = QtWidgets.QDoubleSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voltagecoef_2.setFont(font)
        self.voltagecoef_2.setDecimals(3)
        self.voltagecoef_2.setSingleStep(0.1)
        self.voltagecoef_2.setObjectName("voltagecoef_2")
        self.gridLayout.addWidget(self.voltagecoef_2, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(WSettingsAdvanced)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 4)
        self.label_9 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.WeatherMC = QtWidgets.QSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherMC.setFont(font)
        self.WeatherMC.setObjectName("WeatherMC")
        self.gridLayout.addWidget(self.WeatherMC, 3, 2, 1, 1)
        self.WeatherOKDC = QtWidgets.QSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherOKDC.setFont(font)
        self.WeatherOKDC.setObjectName("WeatherOKDC")
        self.gridLayout.addWidget(self.WeatherOKDC, 2, 2, 1, 1)
        self.voltagemin_2 = QtWidgets.QDoubleSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voltagemin_2.setFont(font)
        self.voltagemin_2.setDecimals(1)
        self.voltagemin_2.setSingleStep(0.1)
        self.voltagemin_2.setObjectName("voltagemin_2")
        self.gridLayout.addWidget(self.voltagemin_2, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.btn_valid = QtWidgets.QPushButton(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.gridLayout.addWidget(self.btn_valid, 10, 3, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 10, 2, 1, 1)
        self.WeatherMinVoltage = QtWidgets.QDoubleSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherMinVoltage.setFont(font)
        self.WeatherMinVoltage.setDecimals(1)
        self.WeatherMinVoltage.setSingleStep(0.1)
        self.WeatherMinVoltage.setObjectName("WeatherMinVoltage")
        self.gridLayout.addWidget(self.WeatherMinVoltage, 3, 0, 1, 1)
        self.voltagemin_1 = QtWidgets.QDoubleSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voltagemin_1.setFont(font)
        self.voltagemin_1.setDecimals(1)
        self.voltagemin_1.setSingleStep(0.1)
        self.voltagemin_1.setObjectName("voltagemin_1")
        self.gridLayout.addWidget(self.voltagemin_1, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 3, 1, 1)
        self.voltagecoef_1 = QtWidgets.QDoubleSpinBox(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voltagecoef_1.setFont(font)
        self.voltagecoef_1.setDecimals(3)
        self.voltagecoef_1.setSingleStep(0.1)
        self.voltagecoef_1.setObjectName("voltagecoef_1")
        self.gridLayout.addWidget(self.voltagecoef_1, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(WSettingsAdvanced)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 0, 1, 4)
        self.label_14 = QtWidgets.QLabel(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 3, 1, 1)
        self.btn_back = QtWidgets.QPushButton(WSettingsAdvanced)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 10, 0, 1, 2)

        self.retranslateUi(WSettingsAdvanced)
        QtCore.QMetaObject.connectSlotsByName(WSettingsAdvanced)

    def retranslateUi(self, WSettingsAdvanced):
        _translate = QtCore.QCoreApplication.translate
        WSettingsAdvanced.setWindowTitle(_translate("WSettingsAdvanced", "Form"))
        self.label_11.setText(_translate("WSettingsAdvanced", "ADC coef[1]"))
        self.label_2.setText(_translate("WSettingsAdvanced", "Weather Station"))
        self.label_9.setText(_translate("WSettingsAdvanced", "Min Voltage[2]"))
        self.label_12.setText(_translate("WSettingsAdvanced", "ADC coef[2]"))
        self.label_13.setText(_translate("WSettingsAdvanced", "Lost Sensor (s)"))
        self.label_10.setText(_translate("WSettingsAdvanced", "Min Voltage (V)"))
        self.label_3.setText(_translate("WSettingsAdvanced", "Min Voltage[1]"))
        self.label.setText(_translate("WSettingsAdvanced", "Advanced Settings"))
        self.btn_valid.setText(_translate("WSettingsAdvanced", "Valid"))
        self.btn_cancel.setText(_translate("WSettingsAdvanced", "Cancel"))
        self.label_15.setText(_translate("WSettingsAdvanced", "Marginal (s)"))
        self.label_4.setText(_translate("WSettingsAdvanced", "Chrono"))
        self.label_14.setText(_translate("WSettingsAdvanced", "OK DC (s)"))
        self.btn_back.setText(_translate("WSettingsAdvanced", "Back to Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettingsAdvanced = QtWidgets.QWidget()
    ui = Ui_WSettingsAdvanced()
    ui.setupUi(WSettingsAdvanced)
    WSettingsAdvanced.show()
    sys.exit(app.exec_())
