# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WSettingsConnectedDevices.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsConnectedDevices(object):
    def setupUi(self, WSettingsConnectedDevices):
        WSettingsConnectedDevices.setObjectName("WSettingsConnectedDevices")
        WSettingsConnectedDevices.resize(397, 247)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WSettingsConnectedDevices.sizePolicy().hasHeightForWidth())
        WSettingsConnectedDevices.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(WSettingsConnectedDevices)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_AnemometerConnect = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_AnemometerConnect.setFont(font)
        self.btn_AnemometerConnect.setObjectName("btn_AnemometerConnect")
        self.gridLayout.addWidget(self.btn_AnemometerConnect, 1, 3, 1, 3)
        self.WeatherStation_Speed = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherStation_Speed.setFont(font)
        self.WeatherStation_Speed.setObjectName("WeatherStation_Speed")
        self.gridLayout.addWidget(self.WeatherStation_Speed, 8, 0, 1, 2)
        self.label = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 6)
        self.WeatherStation_Rain = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherStation_Rain.setFont(font)
        self.WeatherStation_Rain.setObjectName("WeatherStation_Rain")
        self.gridLayout.addWidget(self.WeatherStation_Rain, 8, 4, 1, 2)
        self.btn_base_settings = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_base_settings.setFont(font)
        self.btn_base_settings.setObjectName("btn_base_settings")
        self.gridLayout.addWidget(self.btn_base_settings, 14, 0, 1, 3)
        self.wbtn_settings = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.wbtn_settings.setFont(font)
        self.wbtn_settings.setObjectName("wbtn_settings")
        self.gridLayout.addWidget(self.wbtn_settings, 14, 3, 1, 3)
        self.btn_back = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 15, 0, 1, 6)
        self.btn_valid = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_valid.setFont(font)
        self.btn_valid.setObjectName("btn_valid")
        self.gridLayout.addWidget(self.btn_valid, 16, 3, 1, 3)
        self.btn_cancel = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 16, 0, 1, 3)
        self.line_3 = QtWidgets.QFrame(WSettingsConnectedDevices)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 9, 0, 1, 6)
        self.line = QtWidgets.QFrame(WSettingsConnectedDevices)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 6)
        self.line_2 = QtWidgets.QFrame(WSettingsConnectedDevices)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 6)
        self.AnemometerComboBox = QtWidgets.QComboBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AnemometerComboBox.setFont(font)
        self.AnemometerComboBox.setObjectName("AnemometerComboBox")
        self.AnemometerComboBox.addItem("")
        self.AnemometerComboBox.addItem("")
        self.AnemometerComboBox.addItem("")
        self.gridLayout.addWidget(self.AnemometerComboBox, 2, 0, 1, 3)
        self.btn_AnemometerGetList = QtWidgets.QPushButton(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_AnemometerGetList.setFont(font)
        self.btn_AnemometerGetList.setObjectName("btn_AnemometerGetList")
        self.gridLayout.addWidget(self.btn_AnemometerGetList, 1, 0, 1, 3)
        self.WeatherStation_Dir = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherStation_Dir.setFont(font)
        self.WeatherStation_Dir.setObjectName("WeatherStation_Dir")
        self.gridLayout.addWidget(self.WeatherStation_Dir, 8, 2, 1, 2)
        self.checkBox_Speed = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Speed.setFont(font)
        self.checkBox_Speed.setObjectName("checkBox_Speed")
        self.gridLayout.addWidget(self.checkBox_Speed, 10, 0, 1, 1)
        self.checkBox_Rain = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Rain.setFont(font)
        self.checkBox_Rain.setObjectName("checkBox_Rain")
        self.gridLayout.addWidget(self.checkBox_Rain, 10, 3, 1, 1)
        self.checkBox_Display = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Display.setFont(font)
        self.checkBox_Display.setObjectName("checkBox_Display")
        self.gridLayout.addWidget(self.checkBox_Display, 10, 4, 1, 2)
        self.checkBox_Dir = QtWidgets.QCheckBox(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Dir.setFont(font)
        self.checkBox_Dir.setObjectName("checkBox_Dir")
        self.gridLayout.addWidget(self.checkBox_Dir, 10, 1, 1, 1)
        self.AnemometerStatus = QtWidgets.QLabel(WSettingsConnectedDevices)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AnemometerStatus.setFont(font)
        self.AnemometerStatus.setObjectName("AnemometerStatus")
        self.gridLayout.addWidget(self.AnemometerStatus, 2, 3, 1, 3)

        self.retranslateUi(WSettingsConnectedDevices)
        QtCore.QMetaObject.connectSlotsByName(WSettingsConnectedDevices)

    def retranslateUi(self, WSettingsConnectedDevices):
        _translate = QtCore.QCoreApplication.translate
        WSettingsConnectedDevices.setWindowTitle(_translate("WSettingsConnectedDevices", "Form"))
        self.btn_AnemometerConnect.setText(_translate("WSettingsConnectedDevices", "Connect"))
        self.WeatherStation_Speed.setText(_translate("WSettingsConnectedDevices", "Wind : -1 m/s"))
        self.label.setText(_translate("WSettingsConnectedDevices", "Connected Devices Settings"))
        self.WeatherStation_Rain.setText(_translate("WSettingsConnectedDevices", "Rain : Yes"))
        self.btn_base_settings.setText(_translate("WSettingsConnectedDevices", "Base Settings"))
        self.wbtn_settings.setText(_translate("WSettingsConnectedDevices", "WBtn Settings"))
        self.btn_back.setText(_translate("WSettingsConnectedDevices", "Back to Settings"))
        self.btn_valid.setText(_translate("WSettingsConnectedDevices", "Valid"))
        self.btn_cancel.setText(_translate("WSettingsConnectedDevices", "Cancel"))
        self.AnemometerComboBox.setItemText(0, _translate("WSettingsConnectedDevices", "SDA"))
        self.AnemometerComboBox.setItemText(1, _translate("WSettingsConnectedDevices", "PRO"))
        self.AnemometerComboBox.setItemText(2, _translate("WSettingsConnectedDevices", "JMA"))
        self.btn_AnemometerGetList.setText(_translate("WSettingsConnectedDevices", "Get Anemometer List"))
        self.WeatherStation_Dir.setText(_translate("WSettingsConnectedDevices", "Angle : Nan, 5V"))
        self.checkBox_Speed.setText(_translate("WSettingsConnectedDevices", "Wind"))
        self.checkBox_Rain.setText(_translate("WSettingsConnectedDevices", "Rain"))
        self.checkBox_Display.setText(_translate("WSettingsConnectedDevices", "Display"))
        self.checkBox_Dir.setText(_translate("WSettingsConnectedDevices", "Angle"))
        self.AnemometerStatus.setText(_translate("WSettingsConnectedDevices", "Not connected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WSettingsConnectedDevices = QtWidgets.QWidget()
    ui = Ui_WSettingsConnectedDevices()
    ui.setupUi(WSettingsConnectedDevices)
    WSettingsConnectedDevices.show()
    sys.exit(app.exec_())
