# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt5chrono.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 300)
        MainWindow.setMaximumSize(QtCore.QSize(480, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.pageHome)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 249, 471, 33))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_CheckPICAM = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Btn_CheckPICAM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_CheckPICAM.setFlat(True)
        self.Btn_CheckPICAM.setObjectName("Btn_CheckPICAM")
        self.horizontalLayout_2.addWidget(self.Btn_CheckPICAM)
        self.Btn_Practice = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Btn_Practice.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_Practice.setFlat(True)
        self.Btn_Practice.setObjectName("Btn_Practice")
        self.horizontalLayout_2.addWidget(self.Btn_Practice)
        self.Btn_Chrono = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Btn_Chrono.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_Chrono.setFlat(True)
        self.Btn_Chrono.setObjectName("Btn_Chrono")
        self.horizontalLayout_2.addWidget(self.Btn_Chrono)
        self.layoutWidget = QtWidgets.QWidget(self.pageHome)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 156))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboIP1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboIP1.setMinimumSize(QtCore.QSize(86, 0))
        self.comboIP1.setObjectName("comboIP1")
        self.comboIP1.addItem("")
        self.comboIP1.addItem("")
        self.horizontalLayout_4.addWidget(self.comboIP1)
        self.lineEdit_IP1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_IP1.setReadOnly(True)
        self.lineEdit_IP1.setObjectName("lineEdit_IP1")
        self.horizontalLayout_4.addWidget(self.lineEdit_IP1)
        self.checkBox_IP1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_IP1.setObjectName("checkBox_IP1")
        self.horizontalLayout_4.addWidget(self.checkBox_IP1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboIP2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboIP2.setMinimumSize(QtCore.QSize(86, 0))
        self.comboIP2.setObjectName("comboIP2")
        self.comboIP2.addItem("")
        self.comboIP2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboIP2)
        self.lineEdit__IP2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit__IP2.setReadOnly(True)
        self.lineEdit__IP2.setObjectName("lineEdit__IP2")
        self.horizontalLayout_5.addWidget(self.lineEdit__IP2)
        self.checkBox_IP2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_IP2.setTristate(False)
        self.checkBox_IP2.setObjectName("checkBox_IP2")
        self.horizontalLayout_5.addWidget(self.checkBox_IP2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(86, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.ComboStartIn = QtWidgets.QComboBox(self.layoutWidget)
        self.ComboStartIn.setObjectName("ComboStartIn")
        self.ComboStartIn.addItem("")
        self.ComboStartIn.addItem("")
        self.horizontalLayout_6.addWidget(self.ComboStartIn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.pageHome)
        self.pagePiCAM = QtWidgets.QWidget()
        self.pagePiCAM.setObjectName("pagePiCAM")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.pagePiCAM)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 249, 471, 33))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_PiCam_Refresh = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_PiCam_Refresh.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_PiCam_Refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_PiCam_Refresh.setFlat(True)
        self.Btn_PiCam_Refresh.setObjectName("Btn_PiCam_Refresh")
        self.horizontalLayout_3.addWidget(self.Btn_PiCam_Refresh)
        self.Btn_PiCam_Home = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_PiCam_Home.setFlat(True)
        self.Btn_PiCam_Home.setObjectName("Btn_PiCam_Home")
        self.horizontalLayout_3.addWidget(self.Btn_PiCam_Home)
        self.treeWidget = QtWidgets.QTreeWidget(self.pagePiCAM)
        self.treeWidget.setGeometry(QtCore.QRect(0, 10, 471, 231))
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(140)
        self.treeWidget.header().setMinimumSectionSize(160)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.pagePiCAM)
        self.pagePractice = QtWidgets.QWidget()
        self.pagePractice.setObjectName("pagePractice")
        self.listWidget = QtWidgets.QListWidget(self.pagePractice)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 471, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pagePractice)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 248, 471, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_InStart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Btn_InStart.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_InStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_InStart.setFlat(True)
        self.Btn_InStart.setObjectName("Btn_InStart")
        self.horizontalLayout.addWidget(self.Btn_InStart)
        self.Btn_ResetChrono = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Btn_ResetChrono.setFlat(True)
        self.Btn_ResetChrono.setObjectName("Btn_ResetChrono")
        self.horizontalLayout.addWidget(self.Btn_ResetChrono)
        self.Btn_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Btn_Save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_Save.setFlat(True)
        self.Btn_Save.setObjectName("Btn_Save")
        self.horizontalLayout.addWidget(self.Btn_Save)
        self.Btn_Back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Btn_Back.setFlat(True)
        self.Btn_Back.setObjectName("Btn_Back")
        self.horizontalLayout.addWidget(self.Btn_Back)
        self.stackedWidget.addWidget(self.pagePractice)
        self.pageChrono = QtWidgets.QWidget()
        self.pageChrono.setObjectName("pageChrono")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.pageChrono)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 248, 471, 33))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Btn_ChronoInStart = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoInStart.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_ChronoInStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_ChronoInStart.setFlat(True)
        self.Btn_ChronoInStart.setObjectName("Btn_ChronoInStart")
        self.horizontalLayout_7.addWidget(self.Btn_ChronoInStart)
        self.Btn_ChronoReset = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoReset.setFlat(True)
        self.Btn_ChronoReset.setObjectName("Btn_ChronoReset")
        self.horizontalLayout_7.addWidget(self.Btn_ChronoReset)
        self.Btn_ChronoSave = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_ChronoSave.setFlat(True)
        self.Btn_ChronoSave.setObjectName("Btn_ChronoSave")
        self.horizontalLayout_7.addWidget(self.Btn_ChronoSave)
        self.Btn_ChronoBack = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoBack.setFlat(True)
        self.Btn_ChronoBack.setObjectName("Btn_ChronoBack")
        self.horizontalLayout_7.addWidget(self.Btn_ChronoBack)
        self.stackedWidget.addWidget(self.pageChrono)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionInStart = QtWidgets.QAction(MainWindow)
        self.actionInStart.setObjectName("actionInStart")
        self.actionResetChrono = QtWidgets.QAction(MainWindow)
        self.actionResetChrono.setObjectName("actionResetChrono")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionHomeNext = QtWidgets.QAction(MainWindow)
        self.actionHomeNext.setObjectName("actionHomeNext")
        self.actionCheckPicam = QtWidgets.QAction(MainWindow)
        self.actionCheckPicam.setObjectName("actionCheckPicam")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.comboIP2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_CheckPICAM.setText(_translate("MainWindow", "Check PiCams"))
        self.Btn_Practice.setText(_translate("MainWindow", "Practice"))
        self.Btn_Chrono.setText(_translate("MainWindow", "Chrono"))
        self.comboIP1.setItemText(0, _translate("MainWindow", "IP Left"))
        self.comboIP1.setItemText(1, _translate("MainWindow", "IP Right"))
        self.lineEdit_IP1.setText(_translate("MainWindow", "192.168.0.16"))
        self.checkBox_IP1.setText(_translate("MainWindow", "Connected"))
        self.comboIP2.setItemText(0, _translate("MainWindow", "IP Left"))
        self.comboIP2.setItemText(1, _translate("MainWindow", "IP Right"))
        self.lineEdit__IP2.setText(_translate("MainWindow", "192.168.0.17"))
        self.checkBox_IP2.setText(_translate("MainWindow", "Connected"))
        self.label_3.setText(_translate("MainWindow", "Start In "))
        self.ComboStartIn.setItemText(0, _translate("MainWindow", "Left"))
        self.ComboStartIn.setItemText(1, _translate("MainWindow", "Right"))
        self.Btn_PiCam_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.Btn_PiCam_Home.setText(_translate("MainWindow", "Home"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "PiCAM IP"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Enable"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Position"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "192.168.0.16"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "192.168.0.17"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.Btn_InStart.setText(_translate("MainWindow", "InStart"))
        self.Btn_ResetChrono.setText(_translate("MainWindow", "Reset Chrono"))
        self.Btn_Save.setText(_translate("MainWindow", "Save"))
        self.Btn_Back.setText(_translate("MainWindow", "Home"))
        self.Btn_ChronoInStart.setText(_translate("MainWindow", "InStart"))
        self.Btn_ChronoReset.setText(_translate("MainWindow", "Reset Chrono"))
        self.Btn_ChronoSave.setText(_translate("MainWindow", "Save"))
        self.Btn_ChronoBack.setText(_translate("MainWindow", "Home"))
        self.actionInStart.setText(_translate("MainWindow", "InStart"))
        self.actionResetChrono.setText(_translate("MainWindow", "ResetChrono"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save"))
        self.actionHomeNext.setText(_translate("MainWindow", "HomeNext"))
        self.actionCheckPicam.setText(_translate("MainWindow", "CheckPicam"))
        self.actionCheckPicam.setToolTip(_translate("MainWindow", "CheckPicam"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
