# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qtchrono.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 300)
        MainWindow.setMaximumSize(QtCore.QSize(480, 300))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 301))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageHome = QtGui.QWidget()
        self.pageHome.setObjectName(_fromUtf8("pageHome"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.pageHome)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 249, 471, 33))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Btn_CheckPICAM = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.Btn_CheckPICAM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_CheckPICAM.setFlat(True)
        self.Btn_CheckPICAM.setObjectName(_fromUtf8("Btn_CheckPICAM"))
        self.horizontalLayout_2.addWidget(self.Btn_CheckPICAM)
        self.Btn_Practice = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.Btn_Practice.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_Practice.setFlat(True)
        self.Btn_Practice.setObjectName(_fromUtf8("Btn_Practice"))
        self.horizontalLayout_2.addWidget(self.Btn_Practice)
        self.Btn_Chrono = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.Btn_Chrono.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_Chrono.setFlat(True)
        self.Btn_Chrono.setObjectName(_fromUtf8("Btn_Chrono"))
        self.horizontalLayout_2.addWidget(self.Btn_Chrono)
        self.layoutWidget = QtGui.QWidget(self.pageHome)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 156))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.comboIP1 = QtGui.QComboBox(self.layoutWidget)
        self.comboIP1.setMinimumSize(QtCore.QSize(86, 0))
        self.comboIP1.setObjectName(_fromUtf8("comboIP1"))
        self.comboIP1.addItem(_fromUtf8(""))
        self.comboIP1.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboIP1)
        self.lineEdit_IP1 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_IP1.setReadOnly(True)
        self.lineEdit_IP1.setObjectName(_fromUtf8("lineEdit_IP1"))
        self.horizontalLayout_4.addWidget(self.lineEdit_IP1)
        self.checkBox_IP1 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_IP1.setObjectName(_fromUtf8("checkBox_IP1"))
        self.horizontalLayout_4.addWidget(self.checkBox_IP1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboIP2 = QtGui.QComboBox(self.layoutWidget)
        self.comboIP2.setMinimumSize(QtCore.QSize(86, 0))
        self.comboIP2.setObjectName(_fromUtf8("comboIP2"))
        self.comboIP2.addItem(_fromUtf8(""))
        self.comboIP2.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboIP2)
        self.lineEdit__IP2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit__IP2.setReadOnly(True)
        self.lineEdit__IP2.setObjectName(_fromUtf8("lineEdit__IP2"))
        self.horizontalLayout_5.addWidget(self.lineEdit__IP2)
        self.checkBox_IP2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_IP2.setTristate(False)
        self.checkBox_IP2.setObjectName(_fromUtf8("checkBox_IP2"))
        self.horizontalLayout_5.addWidget(self.checkBox_IP2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(86, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.ComboStartIn = QtGui.QComboBox(self.layoutWidget)
        self.ComboStartIn.setObjectName(_fromUtf8("ComboStartIn"))
        self.ComboStartIn.addItem(_fromUtf8(""))
        self.ComboStartIn.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.ComboStartIn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.pageHome)
        self.pagePiCAM = QtGui.QWidget()
        self.pagePiCAM.setObjectName(_fromUtf8("pagePiCAM"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.pagePiCAM)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 249, 471, 33))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Btn_PiCam_Refresh = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_PiCam_Refresh.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_PiCam_Refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_PiCam_Refresh.setFlat(True)
        self.Btn_PiCam_Refresh.setObjectName(_fromUtf8("Btn_PiCam_Refresh"))
        self.horizontalLayout_3.addWidget(self.Btn_PiCam_Refresh)
        self.Btn_PiCam_Home = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_PiCam_Home.setFlat(True)
        self.Btn_PiCam_Home.setObjectName(_fromUtf8("Btn_PiCam_Home"))
        self.horizontalLayout_3.addWidget(self.Btn_PiCam_Home)
        self.treeWidget = QtGui.QTreeWidget(self.pagePiCAM)
        self.treeWidget.setGeometry(QtCore.QRect(0, 10, 471, 231))
        self.treeWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(140)
        self.treeWidget.header().setMinimumSectionSize(160)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.pagePiCAM)
        self.pagePractice = QtGui.QWidget()
        self.pagePractice.setObjectName(_fromUtf8("pagePractice"))
        self.listWidget = QtGui.QListWidget(self.pagePractice)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 471, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.pagePractice)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 248, 471, 33))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Btn_InStart = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.Btn_InStart.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_InStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_InStart.setFlat(True)
        self.Btn_InStart.setObjectName(_fromUtf8("Btn_InStart"))
        self.horizontalLayout.addWidget(self.Btn_InStart)
        self.Btn_ResetChrono = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.Btn_ResetChrono.setFlat(True)
        self.Btn_ResetChrono.setObjectName(_fromUtf8("Btn_ResetChrono"))
        self.horizontalLayout.addWidget(self.Btn_ResetChrono)
        self.Btn_Save = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.Btn_Save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_Save.setFlat(True)
        self.Btn_Save.setObjectName(_fromUtf8("Btn_Save"))
        self.horizontalLayout.addWidget(self.Btn_Save)
        self.Btn_Back = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.Btn_Back.setFlat(True)
        self.Btn_Back.setObjectName(_fromUtf8("Btn_Back"))
        self.horizontalLayout.addWidget(self.Btn_Back)
        self.stackedWidget.addWidget(self.pagePractice)
        self.pageChrono = QtGui.QWidget()
        self.pageChrono.setObjectName(_fromUtf8("pageChrono"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.pageChrono)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 248, 471, 33))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.Btn_ChronoInStart = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoInStart.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_ChronoInStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_ChronoInStart.setFlat(True)
        self.Btn_ChronoInStart.setObjectName(_fromUtf8("Btn_ChronoInStart"))
        self.horizontalLayout_7.addWidget(self.Btn_ChronoInStart)
        self.Btn_ChronoReset = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoReset.setFlat(True)
        self.Btn_ChronoReset.setObjectName(_fromUtf8("Btn_ChronoReset"))
        self.horizontalLayout_7.addWidget(self.Btn_ChronoReset)
        self.Btn_ChronoSave = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_ChronoSave.setFlat(True)
        self.Btn_ChronoSave.setObjectName(_fromUtf8("Btn_ChronoSave"))
        self.horizontalLayout_7.addWidget(self.Btn_ChronoSave)
        self.Btn_ChronoBack = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ChronoBack.setFlat(True)
        self.Btn_ChronoBack.setObjectName(_fromUtf8("Btn_ChronoBack"))
        self.horizontalLayout_7.addWidget(self.Btn_ChronoBack)
        self.stackedWidget.addWidget(self.pageChrono)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionInStart = QtGui.QAction(MainWindow)
        self.actionInStart.setObjectName(_fromUtf8("actionInStart"))
        self.actionResetChrono = QtGui.QAction(MainWindow)
        self.actionResetChrono.setObjectName(_fromUtf8("actionResetChrono"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionHomeNext = QtGui.QAction(MainWindow)
        self.actionHomeNext.setObjectName(_fromUtf8("actionHomeNext"))
        self.actionCheckPicam = QtGui.QAction(MainWindow)
        self.actionCheckPicam.setObjectName(_fromUtf8("actionCheckPicam"))

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.comboIP2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.Btn_CheckPICAM.setText(_translate("MainWindow", "Check PiCams", None))
        self.Btn_Practice.setText(_translate("MainWindow", "Practice", None))
        self.Btn_Chrono.setText(_translate("MainWindow", "Chrono", None))
        self.comboIP1.setItemText(0, _translate("MainWindow", "IP Left", None))
        self.comboIP1.setItemText(1, _translate("MainWindow", "IP Right", None))
        self.lineEdit_IP1.setText(_translate("MainWindow", "192.168.0.16", None))
        self.checkBox_IP1.setText(_translate("MainWindow", "Connected", None))
        self.comboIP2.setItemText(0, _translate("MainWindow", "IP Left", None))
        self.comboIP2.setItemText(1, _translate("MainWindow", "IP Right", None))
        self.lineEdit__IP2.setText(_translate("MainWindow", "192.168.0.17", None))
        self.checkBox_IP2.setText(_translate("MainWindow", "Connected", None))
        self.label_3.setText(_translate("MainWindow", "Start In ", None))
        self.ComboStartIn.setItemText(0, _translate("MainWindow", "Left", None))
        self.ComboStartIn.setItemText(1, _translate("MainWindow", "Right", None))
        self.Btn_PiCam_Refresh.setText(_translate("MainWindow", "Refresh", None))
        self.Btn_PiCam_Home.setText(_translate("MainWindow", "Home", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "PiCAM IP", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Enable", None))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Position", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "192.168.0.16", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "192.168.0.17", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.Btn_InStart.setText(_translate("MainWindow", "InStart", None))
        self.Btn_ResetChrono.setText(_translate("MainWindow", "Reset Chrono", None))
        self.Btn_Save.setText(_translate("MainWindow", "Save", None))
        self.Btn_Back.setText(_translate("MainWindow", "Home", None))
        self.Btn_ChronoInStart.setText(_translate("MainWindow", "InStart", None))
        self.Btn_ChronoReset.setText(_translate("MainWindow", "Reset Chrono", None))
        self.Btn_ChronoSave.setText(_translate("MainWindow", "Save", None))
        self.Btn_ChronoBack.setText(_translate("MainWindow", "Home", None))
        self.actionInStart.setText(_translate("MainWindow", "InStart", None))
        self.actionResetChrono.setText(_translate("MainWindow", "ResetChrono", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save", None))
        self.actionHomeNext.setText(_translate("MainWindow", "HomeNext", None))
        self.actionCheckPicam.setText(_translate("MainWindow", "CheckPicam", None))
        self.actionCheckPicam.setToolTip(_translate("MainWindow", "CheckPicam", None))

