# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WChrono.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WChrono(object):
    def setupUi(self, WChrono):
        WChrono.setObjectName("WChrono")
        WChrono.resize(435, 291)
        self.gridLayout_2 = QtWidgets.QGridLayout(WChrono)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LapsTime_Wdg = QtWidgets.QListWidget(WChrono)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LapsTime_Wdg.sizePolicy().hasHeightForWidth())
        self.LapsTime_Wdg.setSizePolicy(sizePolicy)
        self.LapsTime_Wdg.setMinimumSize(QtCore.QSize(160, 190))
        self.LapsTime_Wdg.setMaximumSize(QtCore.QSize(200, 16777215))
        self.LapsTime_Wdg.setObjectName("LapsTime_Wdg")
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LapsTime_Wdg.addItem(item)
        self.gridLayout.addWidget(self.LapsTime_Wdg, 0, 1, 1, 1)
        self.Time_label = QtWidgets.QLabel(WChrono)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Time_label.sizePolicy().hasHeightForWidth())
        self.Time_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.Time_label.setFont(font)
        self.Time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Time_label.setObjectName("Time_label")
        self.gridLayout.addWidget(self.Time_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.comboBox = QtWidgets.QComboBox(WChrono)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_Home = QtWidgets.QPushButton(WChrono)
        self.Btn_Home.setFlat(False)
        self.Btn_Home.setObjectName("Btn_Home")
        self.horizontalLayout.addWidget(self.Btn_Home)
        self.Btn_InStart = QtWidgets.QPushButton(WChrono)
        self.Btn_InStart.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.Btn_InStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_InStart.setFlat(False)
        self.Btn_InStart.setObjectName("Btn_InStart")
        self.horizontalLayout.addWidget(self.Btn_InStart)
        self.Btn_Refly = QtWidgets.QPushButton(WChrono)
        self.Btn_Refly.setFlat(False)
        self.Btn_Refly.setObjectName("Btn_Refly")
        self.horizontalLayout.addWidget(self.Btn_Refly)
        self.Btn_Next = QtWidgets.QPushButton(WChrono)
        self.Btn_Next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_Next.setFlat(False)
        self.Btn_Next.setObjectName("Btn_Next")
        self.horizontalLayout.addWidget(self.Btn_Next)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(WChrono)
        QtCore.QMetaObject.connectSlotsByName(WChrono)

    def retranslateUi(self, WChrono):
        _translate = QtCore.QCoreApplication.translate
        WChrono.setWindowTitle(_translate("WChrono", "Form"))
        __sortingEnabled = self.LapsTime_Wdg.isSortingEnabled()
        self.LapsTime_Wdg.setSortingEnabled(False)
        item = self.LapsTime_Wdg.item(0)
        item.setText(_translate("WChrono", "Laps time (S)"))
        item = self.LapsTime_Wdg.item(1)
        item.setText(_translate("WChrono", "1 : XX.XXX"))
        item = self.LapsTime_Wdg.item(2)
        item.setText(_translate("WChrono", "2 : XX.XXX"))
        item = self.LapsTime_Wdg.item(3)
        item.setText(_translate("WChrono", "3 : XX.XXX"))
        item = self.LapsTime_Wdg.item(4)
        item.setText(_translate("WChrono", "4 : XX.XXX"))
        item = self.LapsTime_Wdg.item(5)
        item.setText(_translate("WChrono", "5 : XX.XXX"))
        item = self.LapsTime_Wdg.item(6)
        item.setText(_translate("WChrono", "6 : XX.XXX"))
        item = self.LapsTime_Wdg.item(7)
        item.setText(_translate("WChrono", "7 : XX.XXX"))
        item = self.LapsTime_Wdg.item(8)
        item.setText(_translate("WChrono", "8 : XX.XXX"))
        item = self.LapsTime_Wdg.item(9)
        item.setText(_translate("WChrono", "9 : XX.XXX"))
        item = self.LapsTime_Wdg.item(10)
        item.setText(_translate("WChrono", "10 : XX.XXX"))
        self.LapsTime_Wdg.setSortingEnabled(__sortingEnabled)
        self.Time_label.setText(_translate("WChrono", "30.000"))
        self.comboBox.setItemText(0, _translate("WChrono", "Wait to launch"))
        self.comboBox.setItemText(1, _translate("WChrono", "Launch"))
        self.comboBox.setItemText(2, _translate("WChrono", "In start"))
        self.comboBox.setItemText(3, _translate("WChrono", "Started"))
        self.comboBox.setItemText(4, _translate("WChrono", "In progress"))
        self.comboBox.setItemText(5, _translate("WChrono", "Finish"))
        self.Btn_Home.setText(_translate("WChrono", "Home"))
        self.Btn_InStart.setText(_translate("WChrono", "InStart"))
        self.Btn_Refly.setText(_translate("WChrono", "Refly"))
        self.Btn_Next.setText(_translate("WChrono", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WChrono = QtWidgets.QWidget()
    ui = Ui_WChrono()
    ui.setupUi(WChrono)
    WChrono.show()
    sys.exit(app.exec_())

