# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WHome.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WHome(object):
    def setupUi(self, WHome):
        WHome.setObjectName("WHome")
        WHome.resize(647, 115)
        self.gridLayout = QtWidgets.QGridLayout(WHome)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboIP1 = QtWidgets.QComboBox(WHome)
        self.comboIP1.setMinimumSize(QtCore.QSize(86, 0))
        self.comboIP1.setObjectName("comboIP1")
        self.comboIP1.addItem("")
        self.comboIP1.addItem("")
        self.horizontalLayout_4.addWidget(self.comboIP1)
        self.lineEdit_IP1 = QtWidgets.QLineEdit(WHome)
        self.lineEdit_IP1.setReadOnly(True)
        self.lineEdit_IP1.setObjectName("lineEdit_IP1")
        self.horizontalLayout_4.addWidget(self.lineEdit_IP1)
        self.checkBox_IP1 = QtWidgets.QCheckBox(WHome)
        self.checkBox_IP1.setObjectName("checkBox_IP1")
        self.horizontalLayout_4.addWidget(self.checkBox_IP1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboIP2 = QtWidgets.QComboBox(WHome)
        self.comboIP2.setMinimumSize(QtCore.QSize(86, 0))
        self.comboIP2.setObjectName("comboIP2")
        self.comboIP2.addItem("")
        self.comboIP2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboIP2)
        self.lineEdit__IP2 = QtWidgets.QLineEdit(WHome)
        self.lineEdit__IP2.setReadOnly(True)
        self.lineEdit__IP2.setObjectName("lineEdit__IP2")
        self.horizontalLayout_5.addWidget(self.lineEdit__IP2)
        self.checkBox_IP2 = QtWidgets.QCheckBox(WHome)
        self.checkBox_IP2.setTristate(False)
        self.checkBox_IP2.setObjectName("checkBox_IP2")
        self.horizontalLayout_5.addWidget(self.checkBox_IP2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(WHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(86, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.ComboStartIn = QtWidgets.QComboBox(WHome)
        self.ComboStartIn.setObjectName("ComboStartIn")
        self.ComboStartIn.addItem("")
        self.ComboStartIn.addItem("")
        self.horizontalLayout_6.addWidget(self.ComboStartIn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_CheckPICAM = QtWidgets.QPushButton(WHome)
        self.Btn_CheckPICAM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_CheckPICAM.setFlat(True)
        self.Btn_CheckPICAM.setObjectName("Btn_CheckPICAM")
        self.horizontalLayout_2.addWidget(self.Btn_CheckPICAM)
        self.Btn_Practice = QtWidgets.QPushButton(WHome)
        self.Btn_Practice.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_Practice.setFlat(True)
        self.Btn_Practice.setObjectName("Btn_Practice")
        self.horizontalLayout_2.addWidget(self.Btn_Practice)
        self.Btn_Chrono = QtWidgets.QPushButton(WHome)
        self.Btn_Chrono.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_Chrono.setFlat(True)
        self.Btn_Chrono.setObjectName("Btn_Chrono")
        self.horizontalLayout_2.addWidget(self.Btn_Chrono)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(WHome)
        self.comboIP2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WHome)

    def retranslateUi(self, WHome):
        _translate = QtCore.QCoreApplication.translate
        WHome.setWindowTitle(_translate("WHome", "Form"))
        self.comboIP1.setItemText(0, _translate("WHome", "IP Left"))
        self.comboIP1.setItemText(1, _translate("WHome", "IP Right"))
        self.lineEdit_IP1.setText(_translate("WHome", "192.168.0.16"))
        self.checkBox_IP1.setText(_translate("WHome", "Connected"))
        self.comboIP2.setItemText(0, _translate("WHome", "IP Left"))
        self.comboIP2.setItemText(1, _translate("WHome", "IP Right"))
        self.lineEdit__IP2.setText(_translate("WHome", "192.168.0.17"))
        self.checkBox_IP2.setText(_translate("WHome", "Connected"))
        self.label_3.setText(_translate("WHome", "Start In "))
        self.ComboStartIn.setItemText(0, _translate("WHome", "Left"))
        self.ComboStartIn.setItemText(1, _translate("WHome", "Right"))
        self.Btn_CheckPICAM.setText(_translate("WHome", "Check PiCams"))
        self.Btn_Practice.setText(_translate("WHome", "Practice"))
        self.Btn_Chrono.setText(_translate("WHome", "Chrono"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WHome = QtWidgets.QWidget()
    ui = Ui_WHome()
    ui.setupUi(WHome)
    WHome.show()
    sys.exit(app.exec_())

